baseURL = "https://gelonet.ru/"
languageCode = "ru-ru"
title = "Стороженко Евгений"
theme = "kiss" #документация по ссылке https://themes.gohugo.io/themes/kiss/
copyright = "&copy; <a href=\"https://github.com/ribice\">Emir Ribic</a> 2017"
disqusShortname = "gelonet"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Стороженко  Евгений" # Author full name
authorEmail = "kpa39l@yandex.ru" # Author email
[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

# [params.opengraph.facebook]
# admins = [] # array of Facebook IDs
# appID = ""
# pageID = ""

# [params.opengraph.twitter]
# page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "kpa39l"
github = "kpa39l"
email = "kpa39l@yandex.ru"
codepen = ""
telegram = "kpa39l"
rss = "index.xml" # Add this to show RSS button in social.

# [params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

# [blackfriday]
# hrefTargetBlank = true

# Theme hamingway
# [params.highlight]
# style = "github"
# languages = ["go", "dockerfile"]

# [[params.social]]
# url = "https://github.com/kpa39l"
# fa_icon = "fa-github"

# [[params.social]]
# url = "https://twitter.com/kpa39l"
# fa_icon = "fa-twitter"

# [[params.social]]
# url = "/index.xml"
# fa_icon = "fa-rss"

#Сюда Hugo сохранит сгенерированный сайт
publishdir = "./public/"

# Theme anake
#[[menu.main]]
#  # Отображаемое название раздела
#  name = "Блог"
#
#  # Вес для сортировки пунктов меню,
#  # чем меньше - тем раньше пункт будет отображен
#  weight = 10
#
#
# # Идентификатор родителя для вложенных пунктов,
# # не все темы поддерживают вложенность
#  identifier = "blog"
#
#  # Путь до раздела со статьями,
#  # соответствует имени папки внутри <OWNER>.github.io/content/
#  url = "/blog"