name: Build and Deploy Hugo Blog

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v3
   #   with:
   #     submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.88.0
        TARGET_REPO: kpa39l/kpa39l.github.io
        TARGET_BRANCH: gh-pages
        TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        CNAME: gelonet.ru